### PR TITLE
Fix SignalRConnectionInfo to support negotiate

### PR DESCRIPTION
**Pull request by chenkennt**
Rename properties in SignalRConnectionInfo to comply with SignalR protocol.

### CODE REVIEW

**Comment by chenkennt** [comment]
Fixed

**Comment by anthonychu** [comment]
@chenkennt I don't think the updated client-side JavaScript will work, as CORS in Azure App Service and also the Functions runtime locally have a problem when the request is made with credentials.

https://github.com/Azure/azure-functions-host/issues/620

I recommend changing back to making the negotiate request manually until we can think of a better solution.

**Comment by chenkennt** [comment]
CORS should be a different problem. I would recommend to use function proxy so that both client page and REST API are in the same domain. I'm wondering how does the binding work right now? It's a cross origin request anyway even without this change.

**Comment by anthonychu** [comment]
Not everyone can use proxies to serve their app, and we're recommending static websites in Storage for serverless scenarios. Proxies also require extra steps in tutorials which add to complexity.

This is only a problem when the HTTP request is made with credentials. The simple chat sample works because it is anonymous. The chat with auth example in #22 (and all cross domain EasyAuth examples currently) works because the auth token is passed via a non-standard header `x-zumo-auth`; if it were `Authorization`, it would have necessitated making the call with credentials and it would fail on App Service / Functions CORS.

It was my intention to make this work seamlessly as well, which is why the object was modelled after the negotiate response (except I got the field names wrong 😃). I think we should ship the samples with the explicit call, then work with app service team to fix this.

We can also look at whether we can ship a JS shim to get around this in the meantime that allows the client to make the negotiate call without credentials and pass a custom header like `x-zumo-auth`.

**Comment by chenkennt** [comment]
According to workaround provided in the issue, I'd like to add the workaround to the function code:
```js
  context.res = {
    body: connectionInfo,
    headers: {
      'Access-Control-Allow-Credentials': 'true',
      'Access-Control-Allow-Origin': origin,
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'X-Requested-With'
    }
  };
```
What do you think?

**Comment by anthonychu** [comment]
Sounds good. Please test locally and in Azure to confirm the workaround works. Thanks!

**Comment by chenkennt** [comment]
Added CORS header to functions. To do this I have to change your simplified C# sample back to parse JSON from body.

**Comment by anthonychu** [comment]
Looks good. Let's merge and try to publish to NuGet. Thanks.

**Pull request merged**
